### ISSUE TITLE
Texture Pack

### ISSUE THREAD

**Issue by skylerzap** [igor725/LuaClassic#1]
How do I get the texture pack? i went into got mode and i saw that most of the textures were missing. So how would i get the texture pack? Also how do I get the UID that i need to specify in the addperm command.

**Comment by igor725** [comment]
Better late than never. The project is dead. Now I am working on the [Minecraft Classic server written in C](https://github.com/igor725/cserver).
Server by default does nothing with the game visuals (as long as I remember), so it cannot be the reason for the missing textures.
There is the list of permissions for addperm:
* server.luaexec - Execute Lua code from chat (Example: "#=1+1")
* commands.[command-name] - Execute chat command
